version: "3.3"

services:
  traefik:
    image: "traefik"
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - --api.dashboard=true
      - --api.debug=true
#      - --defaultEntryPoints=http
      - --entryPoints.http.address=:80
      - --log.level=DEBUG
#      - --accessLog=true
#      - --accessLog.filePath=/traefik.log
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.file.filename=/rules.toml # Load dynamic configuration from a file.
      - --providers.file.watch=true # Only works on top level files in the rules folder
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik.igou.homelab`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.entrypoints=http"
        - "traefik.http.routers.api.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$dsJWkbUR$$XBecusIxI2uTt/xcFeXzf0"
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
      placement:
        constraints:
          - "node.role==manager"
          - "node.hostname==helios4"
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik/rules.toml:/rules.toml"

networks:
  proxy:
    external: true

#example app labels
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.igou.homelab`)"
#      - "traefik.http.routers.portainer-rtr.entrypoints=http"
#      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
#      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
#      # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
#      # This is not necessary if you set your default network in Traefik config/parameters
#      # - "traefik.docker.network=your-traefik-network-name"

